### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by alt-romes** [danfran/cabal-macosx#18]
Hi all, I've setup the package and the `Setup.hs` as explained in the README.
However, upon running `cabal build` I was expecting to see an app bundle in the build artifacts but nothing was generated.

I'm trying to build on 9.4 with cabal 3.8. There are no compilation errors and no app bundle output.

How can I make it work? Has anyone been successful on these versions?

Thanks

**Comment by alt-romes** [comment]
I figured it out reading the source:

The name of the executable must match identically the name of the `MacApp`.

Perhaps the README could be edited mentioning it :)

Thanks.
