### ISSUE TITLE
Tests don't build with Cabal >= 2.2

### ISSUE THREAD

**Issue by ElvishJerricco** [danfran/cabal-macosx#13]
```
[3 of 4] Compiling Distribution.MacOSX.Internal.Tests ( tests/Distribution/MacOSX/Internal/Tests.hs, dist/build/tests/tests-tmp/Distribution/MacOSX/Internal/Tests.o )

tests/Distribution/MacOSX/Internal/Tests.hs:46:49: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
46 |     let execs = [ Executable "Dummy One" "/tmp" ExecutableScopeUnknown emptyBuildInfo
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^

tests/Distribution/MacOSX/Internal/Tests.hs:47:51: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
47 |                   , Executable "Dummy Two" "/tmp" ExecutableScopeUnknown  emptyBuildInfo ]
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^

tests/Distribution/MacOSX/Internal/Tests.hs:60:49: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
60 |     let execs = [ Executable "Dummy One" "/tmp" ExecutableScopeUnknown (emptyBuildInfo { buildable = False })
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^

tests/Distribution/MacOSX/Internal/Tests.hs:61:51: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
61 |                   , Executable "Dummy Two" "/tmp" ExecutableScopeUnknown  emptyBuildInfo ]
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^

tests/Distribution/MacOSX/Internal/Tests.hs:73:49: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
73 |     let execs = [ Executable "Dummy One" "/tmp" ExecutableScopeUnknown (emptyBuildInfo { buildable = False })
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^

tests/Distribution/MacOSX/Internal/Tests.hs:74:51: error:
    Data constructor not in scope:
      ExecutableScopeUnknown :: ExecutableScope
   |
74 |                   , Executable "Dummy Two" "/tmp" ExecutableScopeUnknown  emptyBuildInfo ]
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by danfran** [comment]
Fixed. Also verified for versions 2.4 and 3.0 for Cabal.
